version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SQLITE_URL=jdbc:sqlite:/app/identifier.sqlite
    command: ["java", "-cp", ".:/app/libs/*:/app/src", "main"]
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data